### ISSUE TITLE
One zombie process always remaining after handling requests in SID workers

### ISSUE THREAD

**Issue by prajnoha** [sid-project/sid-mvp#24]
After processing requests in SID workers, there's always one zombie process left. This one is cleaned up only on next iteration of event loop handling when the worker's result code is retrieved by master SID process. The problem here is that for some reason, the event loop is not woken up by `SIGCHLD` even though there's `SIGCHLD` handler installed.

The problematic area is around `sd_event_add_child` call and the associated `sd_event_loop` function which should have been woken up by `SIGCHLD` reception.

**Comment by grinrag** [comment]
https://github.com/systemd/systemd/commit/f8f3f9263e51db180bd78a5f3b152aefd25427ee
