### ISSUE TITLE
Support systemd socket activation in SID daemon

### ISSUE THREAD

**Issue by prajnoha** [sid-project/sid-mvp#26]
Opening this issue to not forget about this.

Hand over the open socket FD from systemd to SID so we can use systemd's service socket activation. Check `SD_LISTEN_PID` and `SD_LISTEN_FDS` environment variables and take the preloaded socket FD.

**Comment by grinrag** [comment]
@prajnoha,  the PR #25 will add systemd socket  unit and then this issue will be resolved together with the issue #18, right?

**Comment by prajnoha** [comment]
Resolved with  commit d5ae67b62b9a709ad854e35b6ba8abe4e9aff183
