### ISSUE TITLE
Interrupted writes should be retried

### ISSUE THREAD

**Issue by bmarzins** [sid-project/sid-mvp#42]
Calls like write_buffer() and _do_comms_unix_send() that write to file descriptors should retry if their writes were interrupted before they wrote all of the requested data.

**Comment by prajnoha** [comment]
This is in as of  commit 2eb405648719c26a5c5bf5637cdd3aae3fa0393d (even in some preceding commit, but this one should also have all related fixes around reading/writing and retrying). This is for `buffer_send`/`buffer_write`, the `comms_unix_send`/`comms_unix_send_iovec` is supposed to be low level wrapper around sendmsg/recvmsg so the looping on errors is up to the caller.
